clear
%% Test 1
filenames = {
    'Astra_13_D_Dry_0_120_80_uphill/CleanData.txt',...
    'Astra_13_D_Dry_0_120_80_uphill/Accelerometer.csv',...
    'Astra_13_D_Dry_0_120_80_uphill/Gyroscope.csv',...
    'Astra_13_D_Dry_0_120_80_uphill/Magnetometer.csv',...
    'Astra_13_D_Dry_0_120_80_uphill/Location.csv'};
car_properties = {
    'Opel',...
    'Astra',...
    2008,...
    1.3...
    'Diesel',...
    'AMT',...
    1230,...
    '195/65 R15',...
    'Dry-Uphill',...
    '0-130-70'};
database(1) = prep_the_data(filenames,car_properties);
save('database.mat','database')
%% Test 2
filenames = {
    'Trax_15_P_dry_0_50_up_down/CleanData.txt',...
    'Trax_15_P_dry_0_50_up_down/Accelerometer.csv',...
    'Trax_15_P_dry_0_50_up_down/Gyroscope.csv',...
    'Trax_15_P_dry_0_50_up_down/Magnetometer.csv',...
    'Trax_15_P_dry_0_50_up_down/Location.csv'};
car_properties = {
    'Chevrolet',...
    'Trax',...
    2014,...
    1.5...
    'Petrol',...
    'MT',...
    1380,...
    '205/70 R16',...
    'Dry-Up-Down',...
    '0-50-0'};
database(2) = prep_the_data(filenames,car_properties);

%% Test 2
% filenames = {
%     'xx/CleanData.txt',...
%     'xx/Accelerometer.csv',...
%     'xx/Gyroscope.csv',...
%     'xx/Magnetometer.csv',...
%     'xx/Location.csv'};
% car_properties = {
%     'Opel',...
%     'Astra',...
%     2008,...
%     1.3...
%     'Diesel',...
%     'AMT',...
%     1230,...
%     '195/65 R15',...
%     'Dry-Uphill',...
%     '0-130-70'};
% database(2) = prep_the_data(filenames,car_properties);
